#![forbid(unsafe_code)]

//! Minimal syscall spec generator.
//!
//! This is intentionally small for Phase A.
//!
//! Usage:
//! ```text
//! cargo run -p syscalls-gen -- syscalls/spec/syscalls.toml --out syscalls/generated
//! ```

use std::fs;
use std::path::{Path, PathBuf};

use anyhow::{Context, Result};
use clap::Parser;
use serde::Deserialize;

#[derive(Parser, Debug)]
struct Args {
    /// Path to syscalls TOML spec.
    spec: PathBuf,
    /// Output directory for generated Rust.
    #[arg(long)]
    out: PathBuf,
}

#[derive(Debug, Deserialize)]
struct Spec {
    syscall: Vec<Syscall>,
}

#[derive(Debug, Deserialize)]
struct Syscall {
    name: String,
    #[serde(default)]
    nr: Option<u32>,
    #[serde(default)]
    must: Option<bool>,
    #[serde(default)]
    should: Option<bool>,
    #[serde(default)]
    may: Option<bool>,
}

fn main() -> Result<()> {
    let args = Args::parse();
    let spec_str =
        fs::read_to_string(&args.spec).with_context(|| format!("read {:?}", args.spec))?;
    let spec: Spec = toml::from_str(&spec_str).context("parse TOML")?;

    fs::create_dir_all(&args.out).with_context(|| format!("mkdir {:?}", args.out))?;
    write_syscall_numbers(&spec, &args.out)?;
    Ok(())
}

fn write_syscall_numbers(spec: &Spec, out_dir: &Path) -> Result<()> {
    let mut lines = vec![
        "// @generated by syscalls-gen. DO NOT EDIT.\n".to_string(),
        "//! Syscall numbers (ABI) for Axle.\n".to_string(),
        "#![allow(non_upper_case_globals)]\n".to_string(),
        "pub type SyscallNumber = u32;\n".to_string(),
    ];

    // Assign numbers: explicit nr wins, otherwise sequential.
    let mut next: u32 = 0;
    for sc in &spec.syscall {
        let nr = sc.nr.unwrap_or_else(|| {
            let v = next;
            next = next.wrapping_add(1);
            v
        });
        lines.push(format!(
            "/// {}\npub const {}: SyscallNumber = {};\n",
            doc_contract(sc),
            const_name(&sc.name),
            nr
        ));
    }

    let out_path = out_dir.join("syscall_numbers.rs");
    fs::write(&out_path, lines.concat()).with_context(|| format!("write {:?}", out_path))?;
    Ok(())
}

fn const_name(name: &str) -> String {
    let mut s = String::from("AXLE_SYS_");
    for ch in name.chars() {
        if ch.is_ascii_alphanumeric() {
            s.push(ch.to_ascii_uppercase());
        } else {
            s.push('_');
        }
    }
    s
}

fn doc_contract(sc: &Syscall) -> String {
    let mut tags = Vec::new();
    if sc.must.unwrap_or(false) {
        tags.push("MUST");
    }
    if sc.should.unwrap_or(false) {
        tags.push("SHOULD");
    }
    if sc.may.unwrap_or(false) {
        tags.push("MAY");
    }
    if tags.is_empty() {
        tags.push("UNSPEC");
    }
    format!("Contract: {}", tags.join("/"))
}
