[workspace]

[package]
name = "nexus-kernel-osdk-bin"
version = "0.1.0"
edition = "2024"

[dependencies.nexus-kernel]
path = "/work"
default-features = false

[dependencies.osdk-frame-allocator]
version = "0.18.0"

[dependencies.osdk-heap-allocator]
version = "0.18.0"

[dependencies.ostd]
version = "0.18.0"

[features]
cser-core-dma-recovery = ["nexus-kernel/cser-core-dma-recovery"]
cser-core-reply-recovery = ["nexus-kernel/cser-core-reply-recovery"]
cser-core-tpm-anchor = ["nexus-kernel/cser-core-tpm-anchor"]
cser-production = ["nexus-kernel/cser-production"]
cser-tool-dma-baseline-experiment = ["nexus-kernel/cser-tool-dma-baseline-experiment"]
cser-tool-dma-experiment = ["nexus-kernel/cser-tool-dma-experiment"]
default = ["cser-production"]
