url = "boot://root-starnix-dynamic-tls"
startup = "eager"

[program]
runner = "elf"
binary = "bin/nexus-init"
args = ["nexus-init"]
env = []

[[use]]
kind = "resolver"
name = "boot-resolver"

[[use]]
kind = "runner"
name = "elf"

[[use]]
kind = "runner"
name = "starnix"

[[children]]
name = "linux_dynamic_tls_smoke"
url = "boot://linux-dynamic-tls-smoke"
startup = "eager"
