url = "boot://root-starnix-net-shell"
startup = "eager"

[program]
runner = "elf"
binary = "bin/nexus-init"
args = ["nexus-init"]
env = []

[[use]]
kind = "resolver"
name = "boot-resolver"

[[use]]
kind = "runner"
name = "elf"

[[use]]
kind = "runner"
name = "starnix"

[[children]]
name = "linux_busybox_socket_shell"
url = "boot://linux-busybox-socket-shell"
startup = "eager"
