url = "boot://root"
startup = "eager"

[program]
runner = "elf"
binary = "bin/nexus-init"
args = ["nexus-init"]
env = []

[[use]]
kind = "resolver"
name = "boot-resolver"

[[use]]
kind = "runner"
name = "elf"

[[children]]
name = "echo_provider"
url = "boot://echo-provider"
startup = "eager"

[[children]]
name = "echo_client"
url = "boot://echo-client"
startup = "eager"
