url = "boot://root-starnix-round3"
startup = "eager"

[program]
runner = "elf"
binary = "bin/nexus-init"
args = ["nexus-init"]
env = []

[[use]]
kind = "resolver"
name = "boot-resolver"

[[use]]
kind = "runner"
name = "elf"

[[use]]
kind = "runner"
name = "starnix"

[[children]]
name = "linux_round3_smoke"
url = "boot://linux-round3-smoke"
startup = "eager"
