//! Port: event queue used by `wait_async` and user packets.
//!
//! This is a host-testable semantic model with **explicit** overflow rules:
//! - A Port has a fixed `capacity` in packets.
//! - `kernel_reserve` enforces that user packets cannot consume the last N slots,
//!   preventing starvation of kernel-generated packets.
//! - Kernel-generated packets (from async waits) are never silently dropped. If the
//!   queue is full they become **pending**, and repeated triggers are **merged**
//!   (`count++`, `observed |= ...`).
//!
//! This is intentionally *not* tied to a particular sleep/wakeup mechanism; it is a
//! pure state machine suitable for conformance tests.

use alloc::collections::{BTreeMap, VecDeque};
use alloc::vec::Vec;

use crate::signals::Signals;
use crate::timer::Time;

/// Identifier for a waitable object.
///
/// In kernel this corresponds to a global object id / koid. In host tests we just use `u64`.
pub type WaitableId = u64;

/// Key associated with a port packet (Zircon's `key` field).
pub type PortKey = u64;

/// Port packet kind.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum PacketKind {
    /// A user packet (from `port_queue`).
    User,
    /// A signal packet generated by `wait_async`.
    Signal,
}

/// A simplified port packet.
///
/// This mirrors the most important observable fields of Zircon's packet types.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub struct Packet {
    /// User-provided key.
    pub key: PortKey,
    /// Packet kind.
    pub kind: PacketKind,
    /// For signal packets: the object being observed.
    pub waitable: WaitableId,
    /// For signal packets: watched signal mask that triggered this observer.
    pub trigger: Signals,
    /// For signal packets: observed signals snapshot (often OR-merged on overflow).
    pub observed: Signals,
    /// For signal packets: merged trigger count (>= 1 for signal packets, 0 for user packets).
    pub count: u32,
    /// For signal packets: trigger timestamp; 0 when timestamp delivery was not requested.
    pub timestamp: Time,
    /// For user packets: caller-provided status.
    pub status: i32,
    /// For user packets: raw 32-byte payload.
    pub user: [u64; 4],
}

impl Packet {
    /// Create a user packet.
    pub fn user(key: PortKey) -> Self {
        Self::user_with_data(key, 0, [0; 4])
    }

    /// Create a user packet with explicit status and payload.
    pub fn user_with_data(key: PortKey, status: i32, user: [u64; 4]) -> Self {
        Self {
            key,
            kind: PacketKind::User,
            waitable: 0,
            trigger: Signals::NONE,
            observed: Signals::NONE,
            count: 0,
            timestamp: 0,
            status,
            user,
        }
    }

    /// Create a signal packet.
    pub fn signal(
        key: PortKey,
        waitable: WaitableId,
        trigger: Signals,
        observed: Signals,
        count: u32,
        timestamp: Time,
    ) -> Self {
        Self {
            key,
            kind: PacketKind::Signal,
            waitable,
            trigger,
            observed,
            count,
            timestamp,
            status: 0,
            user: [0; 4],
        }
    }
}

/// Timestamp mode requested for async wait packets.
#[derive(Clone, Copy, Debug, Default, PartialEq, Eq)]
pub enum WaitAsyncTimestamp {
    /// Do not include a timestamp in delivered packets.
    #[default]
    None,
    /// Use the kernel monotonic timeline.
    Monotonic,
    /// Use the kernel boot timeline.
    ///
    /// In current bring-up Axle has no suspend/resume distinction yet, so boot
    /// and monotonic time are sourced from the same monotonic clock.
    Boot,
}

/// Options for an async wait.
#[derive(Clone, Copy, Debug, Default, PartialEq, Eq)]
pub struct WaitAsyncOptions {
    /// Edge-triggered: fire only on a transition from not-satisfied -> satisfied.
    ///
    /// For level-triggered waits, packets can be delivered immediately if already satisfied.
    pub edge_triggered: bool,
    /// Which timestamp mode to include in signal packets, if any.
    pub timestamp: WaitAsyncTimestamp,
}

/// Errors for queue operations.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum PortError {
    /// Queue is full for this operation and the caller should wait and retry.
    ShouldWait,
    /// Async wait already exists for (waitable,key) pair.
    AlreadyExists,
    /// Cancel requested for a non-existent wait.
    NotFound,
}

/// Packet queue backend used by the port state machine.
pub trait PacketQueue: core::fmt::Debug {
    /// Number of queued packets currently stored.
    fn len(&self) -> usize;

    /// Returns `true` if no packets are queued.
    fn is_empty(&self) -> bool {
        self.len() == 0
    }

    /// Push one packet to the back of the queue.
    ///
    /// Returns the original packet when the backend cannot store it.
    fn push_back(&mut self, pkt: Packet) -> Result<(), Packet>;

    /// Pop one packet from the front of the queue.
    fn pop_front(&mut self) -> Option<Packet>;
}

/// Default in-memory packet queue used by host tests and simple kernel bring-up.
#[derive(Debug, Default)]
pub struct VecPortQueue {
    packets: VecDeque<Packet>,
}

impl VecPortQueue {
    /// Create an empty queue with room for at least `capacity` packets.
    pub fn with_capacity(capacity: usize) -> Self {
        Self {
            packets: VecDeque::with_capacity(capacity),
        }
    }
}

impl PacketQueue for VecPortQueue {
    fn len(&self) -> usize {
        self.packets.len()
    }

    fn push_back(&mut self, pkt: Packet) -> Result<(), Packet> {
        self.packets.push_back(pkt);
        Ok(())
    }

    fn pop_front(&mut self) -> Option<Packet> {
        self.packets.pop_front()
    }
}

#[derive(Clone, Copy, Debug)]
struct PendingState {
    count: u32,
    trigger: Signals,
    observed: Signals,
    timestamp: Time,
}

#[derive(Clone, Copy, Debug)]
struct Observer {
    watched: Signals,
    options: WaitAsyncOptions,
    last_satisfied: bool,
    pending: Option<PendingState>,
}

/// A Zircon-like port with reservation + pending merge semantics.
#[derive(Debug)]
pub struct PortState<Q: PacketQueue> {
    capacity: usize,
    kernel_reserve: usize,

    q: Q,
    user_in_q: usize,

    // Observers indexed by (waitable,key).
    observers: BTreeMap<(WaitableId, PortKey), Observer>,
    // Pending observer order (FIFO by first overflow).
    pending_order: VecDeque<(WaitableId, PortKey)>,
}

/// Default port semantic state backed by an in-memory queue.
pub type Port = PortState<VecPortQueue>;

impl Port {
    /// Create a new port backed by the default in-memory queue.
    ///
    /// - `capacity` is in packets.
    /// - `kernel_reserve` reserves that many packet slots for kernel-generated packets.
    pub fn new(capacity: usize, kernel_reserve: usize) -> Self {
        Self::with_queue(
            capacity,
            kernel_reserve,
            VecPortQueue::with_capacity(capacity),
        )
    }
}

impl<Q: PacketQueue> PortState<Q> {
    /// Create a new port backed by `queue`.
    ///
    /// - `capacity` is in packets.
    /// - `kernel_reserve` reserves that many packet slots for kernel-generated packets.
    pub fn with_queue(capacity: usize, kernel_reserve: usize, queue: Q) -> Self {
        assert!(capacity > 0, "capacity must be non-zero");
        assert!(
            kernel_reserve <= capacity,
            "kernel_reserve must be <= capacity"
        );
        Self {
            capacity,
            kernel_reserve,
            q: queue,
            user_in_q: 0,
            observers: BTreeMap::new(),
            pending_order: VecDeque::new(),
        }
    }

    /// Consume the port and return its packet queue backend.
    pub fn into_queue(self) -> Q {
        self.q
    }

    /// Total packets currently queued.
    pub fn len(&self) -> usize {
        self.q.len()
    }

    /// Returns `true` if there are no queued packets.
    pub fn is_empty(&self) -> bool {
        self.q.is_empty()
    }

    /// Current signal state for this port object.
    ///
    /// We follow Zircon's convention where ports become `READABLE` when at least
    /// one packet is queued. `WRITABLE` reflects whether a user packet could be
    /// queued without hitting backpressure.
    pub fn signals(&self) -> Signals {
        let mut s = Signals::NONE;
        if !self.q.is_empty() {
            s = s | Signals::OBJECT_READABLE;
        }
        if self.user_in_q < self.user_quota() && self.q.len() < self.capacity {
            s = s | Signals::OBJECT_WRITABLE;
        }
        s
    }

    /// Queue capacity.
    pub const fn capacity(&self) -> usize {
        self.capacity
    }

    /// Reserved slots for kernel packets.
    pub const fn kernel_reserve(&self) -> usize {
        self.kernel_reserve
    }

    fn user_quota(&self) -> usize {
        self.capacity - self.kernel_reserve
    }

    /// Queue a user packet.
    ///
    /// Returns `ShouldWait` if the user quota is exhausted or the queue is full.
    pub fn queue_user(&mut self, pkt: Packet) -> Result<(), PortError> {
        debug_assert_eq!(pkt.kind, PacketKind::User);
        if self.user_in_q >= self.user_quota() {
            return Err(PortError::ShouldWait);
        }
        if self.q.len() >= self.capacity {
            return Err(PortError::ShouldWait);
        }
        if self.q.push_back(pkt).is_err() {
            return Err(PortError::ShouldWait);
        }
        self.user_in_q += 1;
        Ok(())
    }

    /// Pop one packet (non-blocking).
    ///
    /// After popping, this will opportunistically flush pending kernel packets
    /// into newly freed space.
    pub fn pop(&mut self) -> Result<Packet, PortError> {
        let Some(pkt) = self.q.pop_front() else {
            return Err(PortError::ShouldWait);
        };
        if pkt.kind == PacketKind::User {
            debug_assert!(self.user_in_q > 0);
            self.user_in_q -= 1;
        }
        self.flush_pending();
        Ok(pkt)
    }

    /// Register an async wait on a waitable.
    ///
    /// This is one-shot: when the condition fires and a packet is delivered, the observer is removed.
    ///
    /// If `edge_triggered` is `false` and the condition is already satisfied, an immediate packet
    /// is queued (or becomes pending if full).
    pub fn wait_async(
        &mut self,
        waitable: WaitableId,
        key: PortKey,
        watched: Signals,
        options: WaitAsyncOptions,
        current_signals: Signals,
        current_time: Time,
    ) -> Result<(), PortError> {
        let k = (waitable, key);
        if self.observers.contains_key(&k) {
            return Err(PortError::AlreadyExists);
        }

        let satisfied = current_signals.intersects(watched);
        let obs = Observer {
            watched,
            options,
            last_satisfied: satisfied,
            pending: None,
        };
        self.observers.insert(k, obs);

        // Level-triggered: if already satisfied, queue immediately.
        if satisfied && !options.edge_triggered {
            self.on_signals_changed(waitable, current_signals, current_time);
        }

        Ok(())
    }

    /// Cancel an async wait.
    pub fn cancel(&mut self, waitable: WaitableId, key: PortKey) -> Result<(), PortError> {
        let k = (waitable, key);
        if self.observers.remove(&k).is_none() {
            return Err(PortError::NotFound);
        }
        // If it was pending, it'll be cleaned up lazily when flushing.
        Ok(())
    }

    /// Notify the port that a waitable's signals have changed to `current`.
    ///
    /// This will:
    /// - evaluate observers for that waitable
    /// - enqueue signal packets when conditions fire
    /// - if full, mark observers as pending and merge repeated firings
    pub fn on_signals_changed(&mut self, waitable: WaitableId, current: Signals, now: Time) {
        // Collect matching keys first to avoid borrow checker issues.
        let keys: Vec<(WaitableId, PortKey)> = self
            .observers
            .range((waitable, 0)..=(waitable, u64::MAX))
            .map(|(k, _)| *k)
            .collect();

        for k in keys {
            let fire = {
                let Some(obs) = self.observers.get_mut(&k) else {
                    continue;
                };

                let satisfied = current.intersects(obs.watched);
                let fire = if obs.options.edge_triggered {
                    // Edge: only on false->true transition.
                    !obs.last_satisfied && satisfied
                } else {
                    // Level: any time it's satisfied (one-shot means it should fire once).
                    satisfied
                };

                obs.last_satisfied = satisfied;
                fire
            };

            if fire {
                let trigger = self
                    .observers
                    .get(&k)
                    .map(|obs| obs.watched)
                    .unwrap_or(Signals::NONE);
                self.enqueue_or_pending(k, trigger, current, now);
            }
        }

        // Try flushing pending too (in case signals changed when we already have space).
        self.flush_pending();
    }

    fn enqueue_or_pending(
        &mut self,
        k: (WaitableId, PortKey),
        trigger: Signals,
        current: Signals,
        now: Time,
    ) {
        let timestamp = self
            .observers
            .get(&k)
            .map(|obs| match obs.options.timestamp {
                WaitAsyncTimestamp::None => 0,
                WaitAsyncTimestamp::Monotonic | WaitAsyncTimestamp::Boot => now,
            })
            .unwrap_or(0);

        // If we have space, enqueue now (and remove observer) without borrowing it.
        if self.q.len() < self.capacity {
            let pkt = Packet::signal(k.1, k.0, trigger, current, 1, timestamp);
            let queued = self.q.push_back(pkt);
            debug_assert!(
                queued.is_ok(),
                "port queue overflow after capacity pre-check"
            );
            if queued.is_err() {
                return;
            }
            // remove observer (one-shot).
            let _ = self.observers.remove(&k);
            return;
        }

        // Otherwise, become/merge pending.
        let Some(obs) = self.observers.get_mut(&k) else {
            return;
        };

        match &mut obs.pending {
            None => {
                obs.pending = Some(PendingState {
                    count: 1,
                    trigger,
                    observed: current,
                    timestamp,
                });
                self.pending_order.push_back(k);
            }
            Some(p) => {
                p.count = p.count.saturating_add(1);
                p.observed = p.observed | current;
            }
        }
    }

    fn flush_pending(&mut self) {
        while self.q.len() < self.capacity {
            let Some(k) = self.pending_order.pop_front() else {
                break;
            };

            // The observer might have been canceled or already delivered.
            let Some(obs) = self.observers.get(&k).copied() else {
                continue;
            };
            let Some(p) = obs.pending else {
                continue;
            };

            // Enqueue pending packet to the back (preserves FIFO among already queued packets).
            let pkt = Packet::signal(k.1, k.0, p.trigger, p.observed, p.count, p.timestamp);
            let queued = self.q.push_back(pkt);
            debug_assert!(
                queued.is_ok(),
                "port queue overflow while flushing pending packet"
            );
            if queued.is_err() {
                self.pending_order.push_front(k);
                break;
            }

            // Remove observer (one-shot completion).
            let _ = self.observers.remove(&k);
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn user_quota_enforces_kernel_reserve() {
        let mut port = Port::new(4, 2); // user quota = 2
        port.queue_user(Packet::user(1)).unwrap();
        port.queue_user(Packet::user(2)).unwrap();
        assert_eq!(port.queue_user(Packet::user(3)), Err(PortError::ShouldWait));
        assert_eq!(port.len(), 2);
    }

    #[test]
    fn kernel_event_can_still_queue_when_user_quota_full() {
        let mut port = Port::new(4, 2);
        port.queue_user(Packet::user(1)).unwrap();
        port.queue_user(Packet::user(2)).unwrap();
        assert_eq!(port.len(), 2);

        // Register async wait; a kernel event should be able to enqueue into reserved slots.
        port.wait_async(
            42,
            7,
            Signals::CHANNEL_READABLE,
            WaitAsyncOptions::default(),
            Signals::NONE,
            11,
        )
        .unwrap();

        port.on_signals_changed(42, Signals::CHANNEL_READABLE, 12);
        assert_eq!(port.len(), 3);
        let p = port.pop().unwrap(); // user pkt 1
        assert_eq!(p.kind, PacketKind::User);
        let p = port.pop().unwrap(); // user pkt 2
        assert_eq!(p.kind, PacketKind::User);
        let p = port.pop().unwrap(); // signal pkt
        assert_eq!(p.kind, PacketKind::Signal);
        assert_eq!(p.waitable, 42);
        assert_eq!(p.key, 7);
        assert!(p.observed.intersects(Signals::CHANNEL_READABLE));
    }

    #[test]
    fn pending_merge_and_flush() {
        // capacity 1, reserve 1 => user quota 0. We'll only test kernel packets.
        let mut port = Port::new(1, 1);
        port.wait_async(
            1,
            10,
            Signals::CHANNEL_READABLE,
            WaitAsyncOptions::default(),
            Signals::NONE,
            100,
        )
        .unwrap();

        // First firing enqueues (space available).
        port.on_signals_changed(1, Signals::CHANNEL_READABLE, 101);
        assert_eq!(port.len(), 1);

        // Re-arm another observer; then fill queue; then trigger multiple times -> pending merge.
        port.wait_async(
            1,
            11,
            Signals::CHANNEL_READABLE,
            WaitAsyncOptions::default(),
            Signals::NONE,
            200,
        )
        .unwrap();

        // Queue is full now, so triggers become pending.
        port.on_signals_changed(1, Signals::CHANNEL_READABLE, 201);
        port.on_signals_changed(1, Signals::CHANNEL_READABLE, 202);

        // Drain one packet, should flush pending into freed slot.
        let _ = port.pop().unwrap();
        assert_eq!(port.len(), 1);
        let pkt = port.pop().unwrap();
        assert_eq!(pkt.kind, PacketKind::Signal);
        assert_eq!(pkt.key, 11);
        assert!(pkt.count >= 1);
    }

    #[test]
    fn edge_triggered_requires_transition() {
        let mut port = Port::new(4, 2);
        port.wait_async(
            1,
            99,
            Signals::CHANNEL_READABLE,
            WaitAsyncOptions {
                edge_triggered: true,
                timestamp: WaitAsyncTimestamp::None,
            },
            Signals::CHANNEL_READABLE, // already satisfied at arm time
            300,
        )
        .unwrap();

        // Still satisfied: no transition, so no packet.
        port.on_signals_changed(1, Signals::CHANNEL_READABLE, 301);
        assert_eq!(port.len(), 0);

        // Clear then set: transition fires.
        port.on_signals_changed(1, Signals::NONE, 302);
        port.on_signals_changed(1, Signals::CHANNEL_READABLE, 303);
        assert_eq!(port.len(), 1);
        let pkt = port.pop().unwrap();
        assert_eq!(pkt.key, 99);
    }

    #[test]
    fn timestamp_requested_is_recorded_on_delivery() {
        let mut port = Port::new(4, 2);
        port.wait_async(
            5,
            55,
            Signals::TIMER_SIGNALED,
            WaitAsyncOptions {
                edge_triggered: false,
                timestamp: WaitAsyncTimestamp::Monotonic,
            },
            Signals::NONE,
            1000,
        )
        .unwrap();

        port.on_signals_changed(5, Signals::TIMER_SIGNALED, 1234);
        let pkt = port.pop().unwrap();
        assert_eq!(pkt.kind, PacketKind::Signal);
        assert_eq!(pkt.timestamp, 1234);
    }

    #[test]
    fn pending_merge_keeps_first_timestamp() {
        let mut port = Port::new(1, 1);
        port.wait_async(
            7,
            77,
            Signals::TIMER_SIGNALED,
            WaitAsyncOptions {
                edge_triggered: false,
                timestamp: WaitAsyncTimestamp::Monotonic,
            },
            Signals::TIMER_SIGNALED,
            10,
        )
        .unwrap();

        port.wait_async(
            7,
            78,
            Signals::TIMER_SIGNALED,
            WaitAsyncOptions {
                edge_triggered: false,
                timestamp: WaitAsyncTimestamp::Monotonic,
            },
            Signals::NONE,
            20,
        )
        .unwrap();

        port.on_signals_changed(7, Signals::TIMER_SIGNALED, 21);
        port.on_signals_changed(7, Signals::TIMER_SIGNALED, 22);

        assert_eq!(port.pop().unwrap().timestamp, 10);
        let pkt = port.pop().unwrap();
        assert_eq!(pkt.timestamp, 21);
        assert_eq!(pkt.count, 2);
    }

    #[cfg(feature = "loom")]
    #[test]
    fn loom_pending_signal_flush_preserves_one_shot_delivery() {
        use loom::sync::{Arc, Mutex};
        use loom::thread;

        loom::model(|| {
            let port = Arc::new(Mutex::new(Port::new(2, 1)));
            {
                let mut port = port.lock().unwrap();
                port.queue_user(Packet::user(1)).unwrap();
                port.wait_async(
                    42,
                    7,
                    Signals::CHANNEL_READABLE,
                    WaitAsyncOptions::default(),
                    Signals::NONE,
                    11,
                )
                .unwrap();
            }

            let producer_port = Arc::clone(&port);
            let producer = thread::spawn(move || {
                thread::yield_now();
                let mut port = producer_port.lock().unwrap();
                port.on_signals_changed(42, Signals::CHANNEL_READABLE, 12);
                thread::yield_now();
                port.on_signals_changed(42, Signals::CHANNEL_READABLE, 13);
            });

            let consumer_port = Arc::clone(&port);
            let consumer = thread::spawn(move || {
                thread::yield_now();
                let mut port = consumer_port.lock().unwrap();
                let pkt = port.pop().unwrap();
                assert_eq!(pkt.kind, PacketKind::User);
                assert_eq!(pkt.key, 1);
            });

            producer.join().unwrap();
            consumer.join().unwrap();

            let mut port = port.lock().unwrap();
            assert_eq!(port.len(), 1);
            let pkt = port.pop().unwrap();
            assert_eq!(pkt.kind, PacketKind::Signal);
            assert_eq!(pkt.waitable, 42);
            assert_eq!(pkt.key, 7);
            assert!(pkt.observed.intersects(Signals::CHANNEL_READABLE));
            assert!(pkt.count >= 1);
            assert_eq!(port.pop(), Err(PortError::ShouldWait));
        });
    }

    #[cfg(feature = "loom")]
    #[test]
    fn loom_edge_wait_requires_real_transition_under_reordering() {
        use loom::sync::{Arc, Mutex};
        use loom::thread;

        loom::model(|| {
            let port = Arc::new(Mutex::new(Port::new(4, 2)));
            {
                let mut port = port.lock().unwrap();
                port.wait_async(
                    1,
                    99,
                    Signals::CHANNEL_READABLE,
                    WaitAsyncOptions {
                        edge_triggered: true,
                        timestamp: WaitAsyncTimestamp::None,
                    },
                    Signals::CHANNEL_READABLE,
                    300,
                )
                .unwrap();
            }

            let transition_port = Arc::clone(&port);
            let transition = thread::spawn(move || {
                {
                    let mut port = transition_port.lock().unwrap();
                    port.on_signals_changed(1, Signals::NONE, 301);
                }
                thread::yield_now();
                {
                    let mut port = transition_port.lock().unwrap();
                    port.on_signals_changed(1, Signals::CHANNEL_READABLE, 302);
                }
            });

            let steady_port = Arc::clone(&port);
            let steady = thread::spawn(move || {
                thread::yield_now();
                let mut port = steady_port.lock().unwrap();
                port.on_signals_changed(1, Signals::CHANNEL_READABLE, 303);
            });

            transition.join().unwrap();
            steady.join().unwrap();

            let mut port = port.lock().unwrap();
            assert_eq!(port.len(), 1);
            let pkt = port.pop().unwrap();
            assert_eq!(pkt.kind, PacketKind::Signal);
            assert_eq!(pkt.key, 99);
            assert_eq!(pkt.count, 1);
            assert_eq!(port.pop(), Err(PortError::ShouldWait));
        });
    }
}
