//! Port: event queue used by `wait_async` and user packets.
//!
//! This is a host-testable semantic model with **explicit** overflow rules:
//! - A Port has a fixed `capacity` in packets.
//! - `kernel_reserve` enforces that user packets cannot consume the last N slots,
//!   preventing starvation of kernel-generated packets.
//! - Kernel-generated packets (from async waits) are never silently dropped. If the
//!   queue is full they become **pending**, and repeated triggers are **merged**
//!   (`count++`, `observed |= ...`).
//!
//! This is intentionally *not* tied to a particular sleep/wakeup mechanism; it is a
//! pure state machine suitable for conformance tests.

use alloc::collections::{BTreeMap, VecDeque};
use alloc::vec::Vec;

use crate::signals::Signals;

/// Identifier for a waitable object.
///
/// In kernel this corresponds to a global object id / koid. In host tests we just use `u64`.
pub type WaitableId = u64;

/// Key associated with a port packet (Zircon's `key` field).
pub type PortKey = u64;

/// Port packet kind.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum PacketKind {
    /// A user packet (from `port_queue`).
    User,
    /// A signal packet generated by `wait_async`.
    Signal,
}

/// A simplified port packet.
///
/// This mirrors the most important observable fields of Zircon's packet types.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub struct Packet {
    /// User-provided key.
    pub key: PortKey,
    /// Packet kind.
    pub kind: PacketKind,
    /// For signal packets: the object being observed.
    pub waitable: WaitableId,
    /// For signal packets: observed signals snapshot (often OR-merged on overflow).
    pub observed: Signals,
    /// For signal packets: merged trigger count (>= 1 for signal packets, 0 for user packets).
    pub count: u32,
}

impl Packet {
    /// Create a user packet.
    pub fn user(key: PortKey) -> Self {
        Self {
            key,
            kind: PacketKind::User,
            waitable: 0,
            observed: Signals::NONE,
            count: 0,
        }
    }

    /// Create a signal packet.
    pub fn signal(key: PortKey, waitable: WaitableId, observed: Signals, count: u32) -> Self {
        Self {
            key,
            kind: PacketKind::Signal,
            waitable,
            observed,
            count,
        }
    }
}

/// Options for an async wait.
#[derive(Clone, Copy, Debug, Default, PartialEq, Eq)]
pub struct WaitAsyncOptions {
    /// Edge-triggered: fire only on a transition from not-satisfied -> satisfied.
    ///
    /// For level-triggered waits, packets can be delivered immediately if already satisfied.
    pub edge_triggered: bool,
}

/// Errors for queue operations.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum PortError {
    /// Queue is full for this operation and the caller should wait and retry.
    ShouldWait,
    /// Async wait already exists for (waitable,key) pair.
    AlreadyExists,
    /// Cancel requested for a non-existent wait.
    NotFound,
}

#[derive(Clone, Copy, Debug)]
struct PendingState {
    count: u32,
    observed: Signals,
}

#[derive(Clone, Copy, Debug)]
struct Observer {
    watched: Signals,
    options: WaitAsyncOptions,
    last_satisfied: bool,
    pending: Option<PendingState>,
}

/// A Zircon-like port with reservation + pending merge semantics.
#[derive(Debug)]
pub struct Port {
    capacity: usize,
    kernel_reserve: usize,

    q: VecDeque<Packet>,
    user_in_q: usize,

    // Observers indexed by (waitable,key).
    observers: BTreeMap<(WaitableId, PortKey), Observer>,
    // Pending observer order (FIFO by first overflow).
    pending_order: VecDeque<(WaitableId, PortKey)>,
}

impl Port {
    /// Create a new port.
    ///
    /// - `capacity` is in packets.
    /// - `kernel_reserve` reserves that many packet slots for kernel-generated packets.
    pub fn new(capacity: usize, kernel_reserve: usize) -> Self {
        assert!(capacity > 0, "capacity must be non-zero");
        assert!(
            kernel_reserve <= capacity,
            "kernel_reserve must be <= capacity"
        );
        Self {
            capacity,
            kernel_reserve,
            q: VecDeque::new(),
            user_in_q: 0,
            observers: BTreeMap::new(),
            pending_order: VecDeque::new(),
        }
    }

    /// Total packets currently queued.
    pub fn len(&self) -> usize {
        self.q.len()
    }

    /// Returns `true` if there are no queued packets.
    pub fn is_empty(&self) -> bool {
        self.q.is_empty()
    }

    /// Queue capacity.
    pub const fn capacity(&self) -> usize {
        self.capacity
    }

    /// Reserved slots for kernel packets.
    pub const fn kernel_reserve(&self) -> usize {
        self.kernel_reserve
    }

    fn user_quota(&self) -> usize {
        self.capacity - self.kernel_reserve
    }

    /// Queue a user packet.
    ///
    /// Returns `ShouldWait` if the user quota is exhausted or the queue is full.
    pub fn queue_user(&mut self, pkt: Packet) -> Result<(), PortError> {
        debug_assert_eq!(pkt.kind, PacketKind::User);
        if self.user_in_q >= self.user_quota() {
            return Err(PortError::ShouldWait);
        }
        if self.q.len() >= self.capacity {
            return Err(PortError::ShouldWait);
        }
        self.q.push_back(pkt);
        self.user_in_q += 1;
        Ok(())
    }

    /// Pop one packet (non-blocking).
    ///
    /// After popping, this will opportunistically flush pending kernel packets
    /// into newly freed space.
    pub fn pop(&mut self) -> Result<Packet, PortError> {
        let Some(pkt) = self.q.pop_front() else {
            return Err(PortError::ShouldWait);
        };
        if pkt.kind == PacketKind::User {
            debug_assert!(self.user_in_q > 0);
            self.user_in_q -= 1;
        }
        self.flush_pending();
        Ok(pkt)
    }

    /// Register an async wait on a waitable.
    ///
    /// This is one-shot: when the condition fires and a packet is delivered, the observer is removed.
    ///
    /// If `edge_triggered` is `false` and the condition is already satisfied, an immediate packet
    /// is queued (or becomes pending if full).
    pub fn wait_async(
        &mut self,
        waitable: WaitableId,
        key: PortKey,
        watched: Signals,
        options: WaitAsyncOptions,
        current_signals: Signals,
    ) -> Result<(), PortError> {
        let k = (waitable, key);
        if self.observers.contains_key(&k) {
            return Err(PortError::AlreadyExists);
        }

        let satisfied = current_signals.intersects(watched);
        let obs = Observer {
            watched,
            options,
            last_satisfied: satisfied,
            pending: None,
        };
        self.observers.insert(k, obs);

        // Level-triggered: if already satisfied, queue immediately.
        if satisfied && !options.edge_triggered {
            self.on_signals_changed(waitable, current_signals);
        }

        Ok(())
    }

    /// Cancel an async wait.
    pub fn cancel(&mut self, waitable: WaitableId, key: PortKey) -> Result<(), PortError> {
        let k = (waitable, key);
        if self.observers.remove(&k).is_none() {
            return Err(PortError::NotFound);
        }
        // If it was pending, it'll be cleaned up lazily when flushing.
        Ok(())
    }

    /// Notify the port that a waitable's signals have changed to `current`.
    ///
    /// This will:
    /// - evaluate observers for that waitable
    /// - enqueue signal packets when conditions fire
    /// - if full, mark observers as pending and merge repeated firings
    pub fn on_signals_changed(&mut self, waitable: WaitableId, current: Signals) {
        // Collect matching keys first to avoid borrow checker issues.
        let keys: Vec<(WaitableId, PortKey)> = self
            .observers
            .range((waitable, 0)..=(waitable, u64::MAX))
            .map(|(k, _)| *k)
            .collect();

        for k in keys {
            let fire = {
                let Some(obs) = self.observers.get_mut(&k) else {
                    continue;
                };

                let satisfied = current.intersects(obs.watched);
                let fire = if obs.options.edge_triggered {
                    // Edge: only on false->true transition.
                    !obs.last_satisfied && satisfied
                } else {
                    // Level: any time it's satisfied (one-shot means it should fire once).
                    satisfied
                };

                obs.last_satisfied = satisfied;
                fire
            };

            if fire {
                self.enqueue_or_pending(k, current);
            }
        }

        // Try flushing pending too (in case signals changed when we already have space).
        self.flush_pending();
    }

    fn enqueue_or_pending(&mut self, k: (WaitableId, PortKey), current: Signals) {
        // If we have space, enqueue now (and remove observer) without borrowing it.
        if self.q.len() < self.capacity {
            let pkt = Packet::signal(k.1, k.0, current, 1);
            self.q.push_back(pkt);
            // remove observer (one-shot).
            let _ = self.observers.remove(&k);
            return;
        }

        // Otherwise, become/merge pending.
        let Some(obs) = self.observers.get_mut(&k) else {
            return;
        };

        match &mut obs.pending {
            None => {
                obs.pending = Some(PendingState {
                    count: 1,
                    observed: current,
                });
                self.pending_order.push_back(k);
            }
            Some(p) => {
                p.count = p.count.saturating_add(1);
                p.observed = p.observed | current;
            }
        }
    }

    fn flush_pending(&mut self) {
        while self.q.len() < self.capacity {
            let Some(k) = self.pending_order.pop_front() else {
                break;
            };

            // The observer might have been canceled or already delivered.
            let Some(obs) = self.observers.get(&k).copied() else {
                continue;
            };
            let Some(p) = obs.pending else {
                continue;
            };

            // Enqueue pending packet to the back (preserves FIFO among already queued packets).
            let pkt = Packet::signal(k.1, k.0, p.observed, p.count);
            self.q.push_back(pkt);

            // Remove observer (one-shot completion).
            let _ = self.observers.remove(&k);
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn user_quota_enforces_kernel_reserve() {
        let mut port = Port::new(4, 2); // user quota = 2
        port.queue_user(Packet::user(1)).unwrap();
        port.queue_user(Packet::user(2)).unwrap();
        assert_eq!(port.queue_user(Packet::user(3)), Err(PortError::ShouldWait));
        assert_eq!(port.len(), 2);
    }

    #[test]
    fn kernel_event_can_still_queue_when_user_quota_full() {
        let mut port = Port::new(4, 2);
        port.queue_user(Packet::user(1)).unwrap();
        port.queue_user(Packet::user(2)).unwrap();
        assert_eq!(port.len(), 2);

        // Register async wait; a kernel event should be able to enqueue into reserved slots.
        port.wait_async(
            42,
            7,
            Signals::CHANNEL_READABLE,
            WaitAsyncOptions::default(),
            Signals::NONE,
        )
        .unwrap();

        port.on_signals_changed(42, Signals::CHANNEL_READABLE);
        assert_eq!(port.len(), 3);
        let p = port.pop().unwrap(); // user pkt 1
        assert_eq!(p.kind, PacketKind::User);
        let p = port.pop().unwrap(); // user pkt 2
        assert_eq!(p.kind, PacketKind::User);
        let p = port.pop().unwrap(); // signal pkt
        assert_eq!(p.kind, PacketKind::Signal);
        assert_eq!(p.waitable, 42);
        assert_eq!(p.key, 7);
        assert!(p.observed.intersects(Signals::CHANNEL_READABLE));
    }

    #[test]
    fn pending_merge_and_flush() {
        // capacity 1, reserve 1 => user quota 0. We'll only test kernel packets.
        let mut port = Port::new(1, 1);
        port.wait_async(
            1,
            10,
            Signals::CHANNEL_READABLE,
            WaitAsyncOptions::default(),
            Signals::NONE,
        )
        .unwrap();

        // First firing enqueues (space available).
        port.on_signals_changed(1, Signals::CHANNEL_READABLE);
        assert_eq!(port.len(), 1);

        // Re-arm another observer; then fill queue; then trigger multiple times -> pending merge.
        port.wait_async(
            1,
            11,
            Signals::CHANNEL_READABLE,
            WaitAsyncOptions::default(),
            Signals::NONE,
        )
        .unwrap();

        // Queue is full now, so triggers become pending.
        port.on_signals_changed(1, Signals::CHANNEL_READABLE);
        port.on_signals_changed(1, Signals::CHANNEL_READABLE);

        // Drain one packet, should flush pending into freed slot.
        let _ = port.pop().unwrap();
        assert_eq!(port.len(), 1);
        let pkt = port.pop().unwrap();
        assert_eq!(pkt.kind, PacketKind::Signal);
        assert_eq!(pkt.key, 11);
        assert!(pkt.count >= 1);
    }

    #[test]
    fn edge_triggered_requires_transition() {
        let mut port = Port::new(4, 2);
        port.wait_async(
            1,
            99,
            Signals::CHANNEL_READABLE,
            WaitAsyncOptions {
                edge_triggered: true,
            },
            Signals::CHANNEL_READABLE, // already satisfied at arm time
        )
        .unwrap();

        // Still satisfied: no transition, so no packet.
        port.on_signals_changed(1, Signals::CHANNEL_READABLE);
        assert_eq!(port.len(), 0);

        // Clear then set: transition fires.
        port.on_signals_changed(1, Signals::NONE);
        port.on_signals_changed(1, Signals::CHANNEL_READABLE);
        assert_eq!(port.len(), 1);
        let pkt = port.pop().unwrap();
        assert_eq!(pkt.key, 99);
    }
}
