//! Port queue semantics used by user packets and reactor-delivered signal packets.
//!
//! This is a host-testable semantic model with explicit overflow rules:
//! - A Port has a fixed `capacity` in packets.
//! - `kernel_reserve` enforces that user packets cannot consume the last N slots,
//!   preventing starvation of kernel-generated packets.
//! - Kernel-generated packets are admitted up to total capacity.
//!
//! Async wait observer state lives in `observer.rs`; `PortState` is only the packet
//! queue and readiness surface.

use alloc::collections::VecDeque;

use crate::signals::Signals;
use crate::timer::Time;

/// Identifier for a waitable object.
///
/// In kernel this corresponds to a global object id / koid. In host tests we just use `u64`.
pub type WaitableId = u64;

/// Key associated with a port packet (Zircon's `key` field).
pub type PortKey = u64;

/// Port packet kind.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum PacketKind {
    /// A user packet (from `port_queue`).
    User,
    /// A signal packet generated by `wait_async`.
    Signal,
}

/// A simplified port packet.
///
/// This mirrors the most important observable fields of Zircon's packet types.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub struct Packet {
    /// User-provided key.
    pub key: PortKey,
    /// Packet kind.
    pub kind: PacketKind,
    /// For signal packets: the object being observed.
    pub waitable: WaitableId,
    /// For signal packets: watched signal mask that triggered this observer.
    pub trigger: Signals,
    /// For signal packets: observed signals snapshot (often OR-merged on overflow).
    pub observed: Signals,
    /// For signal packets: merged trigger count (>= 1 for signal packets, 0 for user packets).
    pub count: u32,
    /// For signal packets: trigger timestamp; 0 when timestamp delivery was not requested.
    pub timestamp: Time,
    /// For user packets: caller-provided status.
    pub status: i32,
    /// For user packets: raw 32-byte payload.
    pub user: [u64; 4],
}

impl Packet {
    /// Create a user packet.
    pub fn user(key: PortKey) -> Self {
        Self::user_with_data(key, 0, [0; 4])
    }

    /// Create a user packet with explicit status and payload.
    pub fn user_with_data(key: PortKey, status: i32, user: [u64; 4]) -> Self {
        Self {
            key,
            kind: PacketKind::User,
            waitable: 0,
            trigger: Signals::NONE,
            observed: Signals::NONE,
            count: 0,
            timestamp: 0,
            status,
            user,
        }
    }

    /// Create a signal packet.
    pub fn signal(
        key: PortKey,
        waitable: WaitableId,
        trigger: Signals,
        observed: Signals,
        count: u32,
        timestamp: Time,
    ) -> Self {
        Self {
            key,
            kind: PacketKind::Signal,
            waitable,
            trigger,
            observed,
            count,
            timestamp,
            status: 0,
            user: [0; 4],
        }
    }
}

/// Timestamp mode requested for async wait packets.
#[derive(Clone, Copy, Debug, Default, PartialEq, Eq)]
pub enum WaitAsyncTimestamp {
    /// Do not include a timestamp in delivered packets.
    #[default]
    None,
    /// Use the kernel monotonic timeline.
    Monotonic,
    /// Use the kernel boot timeline.
    ///
    /// In current bring-up Axle has no suspend/resume distinction yet, so boot
    /// and monotonic time are sourced from the same monotonic clock.
    Boot,
}

/// Options for an async wait.
#[derive(Clone, Copy, Debug, Default, PartialEq, Eq)]
pub struct WaitAsyncOptions {
    /// Edge-triggered: fire only on a transition from not-satisfied -> satisfied.
    ///
    /// For level-triggered waits, packets can be delivered immediately if already satisfied.
    pub edge_triggered: bool,
    /// Which timestamp mode to include in signal packets, if any.
    pub timestamp: WaitAsyncTimestamp,
}

/// Errors used by port queue and observer operations.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum PortError {
    /// Queue is full for this operation and the caller should wait and retry.
    ShouldWait,
    /// Async wait already exists for a given registration key.
    AlreadyExists,
    /// Cancel requested for a non-existent wait.
    NotFound,
}

/// Packet queue backend used by the port state machine.
pub trait PacketQueue: core::fmt::Debug {
    /// Number of queued packets currently stored.
    fn len(&self) -> usize;

    /// Returns `true` if no packets are queued.
    fn is_empty(&self) -> bool {
        self.len() == 0
    }

    /// Push one packet to the back of the queue.
    ///
    /// Returns the original packet when the backend cannot store it.
    fn push_back(&mut self, pkt: Packet) -> Result<(), Packet>;

    /// Pop one packet from the front of the queue.
    fn pop_front(&mut self) -> Option<Packet>;
}

/// Default in-memory packet queue used by host tests and simple kernel bring-up.
#[derive(Debug, Default)]
pub struct VecPortQueue {
    packets: VecDeque<Packet>,
}

impl VecPortQueue {
    /// Create an empty queue with room for at least `capacity` packets.
    pub fn with_capacity(capacity: usize) -> Self {
        Self {
            packets: VecDeque::with_capacity(capacity),
        }
    }
}

impl PacketQueue for VecPortQueue {
    fn len(&self) -> usize {
        self.packets.len()
    }

    fn push_back(&mut self, pkt: Packet) -> Result<(), Packet> {
        self.packets.push_back(pkt);
        Ok(())
    }

    fn pop_front(&mut self) -> Option<Packet> {
        self.packets.pop_front()
    }
}

#[derive(Clone, Copy, Debug)]
struct KernelReserveTicket;

/// A Zircon-like port queue with reservation semantics.
#[derive(Debug)]
pub struct PortState<Q: PacketQueue> {
    capacity: usize,
    kernel_reserve: usize,
    q: Q,
    user_in_q: usize,
}

/// Default port semantic state backed by an in-memory queue.
pub type Port = PortState<VecPortQueue>;

impl Port {
    /// Create a new port backed by the default in-memory queue.
    ///
    /// - `capacity` is in packets.
    /// - `kernel_reserve` reserves that many packet slots for kernel-generated packets.
    pub fn new(capacity: usize, kernel_reserve: usize) -> Self {
        Self::with_queue(
            capacity,
            kernel_reserve,
            VecPortQueue::with_capacity(capacity),
        )
    }
}

impl<Q: PacketQueue> PortState<Q> {
    /// Create a new port backed by `queue`.
    ///
    /// - `capacity` is in packets.
    /// - `kernel_reserve` reserves that many packet slots for kernel-generated packets.
    pub fn with_queue(capacity: usize, kernel_reserve: usize, queue: Q) -> Self {
        assert!(capacity > 0, "capacity must be non-zero");
        assert!(
            kernel_reserve <= capacity,
            "kernel_reserve must be <= capacity"
        );
        Self {
            capacity,
            kernel_reserve,
            q: queue,
            user_in_q: 0,
        }
    }

    /// Consume the port and return its packet queue backend.
    pub fn into_queue(self) -> Q {
        self.q
    }

    /// Total packets currently queued.
    pub fn len(&self) -> usize {
        self.q.len()
    }

    /// Returns `true` if there are no queued packets.
    pub fn is_empty(&self) -> bool {
        self.q.is_empty()
    }

    /// Current signal state for this port object.
    ///
    /// We follow Zircon's convention where ports become `READABLE` when at least
    /// one packet is queued. `WRITABLE` reflects whether a user packet could be
    /// queued without hitting backpressure.
    pub fn signals(&self) -> Signals {
        let mut s = Signals::NONE;
        if !self.q.is_empty() {
            s = s | Signals::OBJECT_READABLE;
        }
        if self.user_in_q < self.user_quota() && self.q.len() < self.capacity {
            s = s | Signals::OBJECT_WRITABLE;
        }
        s
    }

    /// Queue capacity.
    pub const fn capacity(&self) -> usize {
        self.capacity
    }

    /// Reserved slots for kernel packets.
    pub const fn kernel_reserve(&self) -> usize {
        self.kernel_reserve
    }

    fn user_quota(&self) -> usize {
        self.capacity - self.kernel_reserve
    }

    fn reserve_kernel_slot(&self) -> Option<KernelReserveTicket> {
        (self.q.len() < self.capacity).then_some(KernelReserveTicket)
    }

    /// Queue a user packet.
    ///
    /// Returns `ShouldWait` if the user quota is exhausted or the queue is full.
    pub fn queue_user(&mut self, pkt: Packet) -> Result<(), PortError> {
        debug_assert_eq!(pkt.kind, PacketKind::User);
        if self.user_in_q >= self.user_quota() {
            return Err(PortError::ShouldWait);
        }
        if self.q.len() >= self.capacity {
            return Err(PortError::ShouldWait);
        }
        if self.q.push_back(pkt).is_err() {
            return Err(PortError::ShouldWait);
        }
        self.user_in_q += 1;
        Ok(())
    }

    /// Queue one kernel-generated packet.
    ///
    /// Kernel packets can consume the reserved portion of the queue but still
    /// cannot exceed total capacity.
    pub fn queue_kernel(&mut self, pkt: Packet) -> Result<(), PortError> {
        debug_assert_ne!(pkt.kind, PacketKind::User);
        let _ticket = self.reserve_kernel_slot().ok_or(PortError::ShouldWait)?;
        if self.q.push_back(pkt).is_err() {
            return Err(PortError::ShouldWait);
        }
        Ok(())
    }

    /// Pop one packet (non-blocking).
    pub fn pop(&mut self) -> Result<Packet, PortError> {
        let Some(pkt) = self.q.pop_front() else {
            return Err(PortError::ShouldWait);
        };
        if pkt.kind == PacketKind::User {
            debug_assert!(self.user_in_q > 0);
            self.user_in_q -= 1;
        }
        Ok(pkt)
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn user_quota_enforces_kernel_reserve() {
        let mut port = Port::new(4, 2);
        port.queue_user(Packet::user(1)).unwrap();
        port.queue_user(Packet::user(2)).unwrap();
        assert_eq!(port.queue_user(Packet::user(3)), Err(PortError::ShouldWait));
        assert_eq!(port.len(), 2);
    }

    #[test]
    fn kernel_packet_can_use_reserved_slot() {
        let mut port = Port::new(4, 2);
        port.queue_user(Packet::user(1)).unwrap();
        port.queue_user(Packet::user(2)).unwrap();
        assert_eq!(port.len(), 2);
        port.queue_kernel(Packet::signal(
            7,
            42,
            Signals::CHANNEL_READABLE,
            Signals::CHANNEL_READABLE,
            1,
            12,
        ))
        .unwrap();
        assert_eq!(port.len(), 3);
    }

    #[test]
    fn kernel_packet_still_obeys_total_capacity() {
        let mut port = Port::new(2, 1);
        port.queue_user(Packet::user(1)).unwrap();
        port.queue_kernel(Packet::signal(
            2,
            10,
            Signals::TIMER_SIGNALED,
            Signals::TIMER_SIGNALED,
            1,
            99,
        ))
        .unwrap();
        assert_eq!(
            port.queue_kernel(Packet::signal(
                3,
                10,
                Signals::TIMER_SIGNALED,
                Signals::TIMER_SIGNALED,
                1,
                100,
            )),
            Err(PortError::ShouldWait)
        );
    }
}
