name: ci

on:
  push:
  pull_request:

jobs:
  host:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v31
      - name: all gates
        run: nix develop -c just test-all
